"""Generate a Megatron-LM launch shell script for the current configuration.

The shape follows ``third_party/Megatron-LM/examples/*``: a header with env
vars, a ``torchrun`` invocation, and the ``pretrain_gpt.py`` args.

Defaults are tuned for "drop in and inspect" rather than "production":
``--mock-data`` is on, checkpoint save is off, TensorBoard / W&B are off,
``--log-interval 1``.
"""

from __future__ import annotations

from projection.configs import (
    ModelConfig,
    OptimizerKind,
    ParallelConfig,
    Precision,
    TrainingHyperparameters,
    Workload,
)

_INDENT = "    "


def generate_megatron_script(
    model: ModelConfig,
    parallel: ParallelConfig,
    workload: Workload,
    hyperparameters: TrainingHyperparameters,
    *,
    num_gpus: int,
    nproc_per_node: int = 8,
) -> str:
    nnodes = max(1, (num_gpus + nproc_per_node - 1) // nproc_per_node)
    args = _collect_args(model, parallel, workload, hyperparameters)
    args_block = "\n".join(f"{_INDENT}{a}" for a in args)

    header = f"""\
#!/usr/bin/env bash
# Generated by Megatron-LM-Projection for {model.name}.
# Mock data is used by default. Checkpoint save, TensorBoard and W&B are off.

set -euo pipefail

GPUS_PER_NODE={nproc_per_node}
NNODES={nnodes}
WORLD_SIZE=$((GPUS_PER_NODE * NNODES))
MASTER_ADDR=${{MASTER_ADDR:-localhost}}
MASTER_PORT=${{MASTER_PORT:-6000}}
NODE_RANK=${{NODE_RANK:-0}}

DISTRIBUTED_ARGS=(
    --nproc_per_node $GPUS_PER_NODE
    --nnodes $NNODES
    --node_rank $NODE_RANK
    --master_addr $MASTER_ADDR
    --master_port $MASTER_PORT
)

ARGS=(
{args_block}
)

torchrun "${{DISTRIBUTED_ARGS[@]}}" pretrain_gpt.py "${{ARGS[@]}}"
"""
    return header


def _collect_args(
    model: ModelConfig,
    parallel: ParallelConfig,
    workload: Workload,
    hp: TrainingHyperparameters,
) -> list[str]:
    a = model.architecture
    att = model.attention
    mlp = model.mlp

    args: list[str] = [
        f"--num-layers {a.num_layers}",
        f"--hidden-size {a.hidden_size}",
        f"--ffn-hidden-size {a.ffn_hidden_size}",
        f"--num-attention-heads {att.num_attention_heads}",
        f"--max-position-embeddings {a.max_position_embeddings}",
        f"--seq-length {workload.seq_length}",
        f"--micro-batch-size {workload.micro_batch_size}",
        f"--global-batch-size {workload.global_batch_size}",
        f"--make-vocab-size-divisible-by {a.make_vocab_size_divisible_by}",
        f"--lr {hp.lr}",
        f"--min-lr {hp.min_lr}",
        f"--train-iters {hp.train_iters}",
        f"--weight-decay {hp.weight_decay}",
        f"--clip-grad {hp.clip_grad}",
        f"--adam-beta1 {hp.adam_beta1}",
        f"--adam-beta2 {hp.adam_beta2}",
        f"--adam-eps {hp.adam_eps}",
        f"--attention-dropout {att.attention_dropout}",
        "--hidden-dropout 0.0",
        f"--normalization {model.norm.normalization}",
        f"--norm-epsilon {model.norm.layernorm_epsilon}",
        f"--position-embedding-type {model.position_embedding.position_embedding_type}",
    ]

    if (
        att.num_query_groups
        and att.num_query_groups != att.num_attention_heads
        and not att.use_mla
        and not att.use_deepseek_v4
    ):
        args.append("--group-query-attention")
        args.append(f"--num-query-groups {att.num_query_groups}")
    if att.kv_channels:
        args.append(f"--kv-channels {att.kv_channels}")
    if att.add_qkv_bias:
        args.append("--add-qkv-bias")
    if not mlp.add_bias_linear:
        args.append("--disable-bias-linear")
    if mlp.swiglu:
        args.append("--swiglu")
    if a.untie_embeddings_and_output_weights:
        args.append("--untie-embeddings-and-output-weights")

    if model.position_embedding.position_embedding_type == "rope":
        args.append("--use-rotary-position-embeddings")
        args.append(f"--rotary-base {int(model.position_embedding.rotary_base)}")
        args.append(f"--rotary-percent {model.position_embedding.rotary_percent}")

    if att.use_mla:
        args.append("--multi-latent-attention")
        if att.q_lora_rank is not None:
            args.append(f"--q-lora-rank {att.q_lora_rank}")
        args.append(f"--kv-lora-rank {att.kv_lora_rank}")
        args.append(f"--qk-head-dim {att.qk_nope_head_dim}")
        args.append(f"--qk-pos-emb-head-dim {att.qk_rope_head_dim}")
        args.append(f"--v-head-dim {att.v_head_dim}")

    if att.use_deepseek_v4 and model.hybrid_attention is not None:
        hyb = model.hybrid_attention
        hc = model.hyper_connection
        # DeepSeek-V4 specific flags. These are NOT present in upstream
        # Megatron-LM today — they mirror the names used by Primus's V4 patch
        # set (see third_party/Primus/primus/configs/models/megatron/
        # deepseek_v4_base.yaml). The script is intended as a configuration
        # blueprint, not a turnkey launch script for stock Megatron.
        args.append("# ---------- DeepSeek-V4 hybrid attention ----------")
        args.append("--hybrid-attention-enabled")
        args.append("--use-deepseek-v4")
        if att.q_lora_rank is not None:
            args.append(f"--q-lora-rank {att.q_lora_rank}")
        if att.o_lora_rank is not None:
            args.append(f"--o-lora-rank {att.o_lora_rank}")
        args.append(f"--o-groups {att.o_groups}")
        ratios_str = ",".join(str(r) for r in hyb.compress_ratios)
        args.append(f"--compress-ratios '[{ratios_str}]'")
        args.append(f"--compress-rope-theta {int(hyb.compress_rope_theta)}")
        if hyb.attn_sliding_window > 0:
            args.append(f"--attn-sliding-window {hyb.attn_sliding_window}")
        if hyb.attn_sink:
            args.append("--attn-sink")
        if hyb.index_topk > 0:
            args.append(f"--index-topk {hyb.index_topk}")
            args.append(f"--index-head-dim {hyb.index_head_dim}")
            args.append(f"--index-n-heads {hyb.index_n_heads}")
        if hc.enabled:
            args.append(f"--hc-mult {hc.hc_mult}")
            args.append(f"--hc-sinkhorn-iters {hc.sinkhorn_iters}")
        if model.mtp.num_layers > 0:
            args.append(f"--mtp-num-layers {model.mtp.num_layers}")
            if model.mtp.use_separate_hc_head:
                args.append("--mtp-use-separate-hc-head")
        if model.moe.num_hash_layers > 0:
            args.append(f"--num-hash-layers {model.moe.num_hash_layers}")
        if model.moe.router_score_function != "softmax":
            args.append(f"--moe-router-score-function {model.moe.router_score_function}")
        if model.mlp.swiglu_limit > 0:
            args.append(f"--swiglu-limit {model.mlp.swiglu_limit}")

    if model.moe.enabled:
        args.append(f"--num-experts {model.moe.num_routed_experts}")
        args.append(f"--moe-router-topk {model.moe.moe_router_topk}")
        args.append(f"--moe-ffn-hidden-size {model.moe.moe_ffn_hidden_size}")
        if model.moe.num_shared_experts > 0:
            args.append(
                f"--moe-shared-expert-intermediate-size "
                f"{model.moe.moe_ffn_hidden_size * model.moe.num_shared_experts}"
            )
        if model.moe.first_k_dense_replace > 0:
            args.append(
                f"--moe-layer-freq '[0]*{model.moe.first_k_dense_replace}+[1]*"
                f"{a.num_layers - model.moe.first_k_dense_replace}'"
            )

    args.append(f"--tensor-model-parallel-size {parallel.tensor_model_parallel_size}")
    args.append(f"--pipeline-model-parallel-size {parallel.pipeline_model_parallel_size}")
    if parallel.context_parallel_size > 1:
        args.append(f"--context-parallel-size {parallel.context_parallel_size}")
    if parallel.expert_model_parallel_size > 1:
        args.append(f"--expert-model-parallel-size {parallel.expert_model_parallel_size}")
    if (
        parallel.moe_folding
        and parallel.expert_tensor_parallel_size is not None
        and parallel.expert_tensor_parallel_size != parallel.tensor_model_parallel_size
    ):
        args.append(f"--expert-tensor-parallel-size {parallel.expert_tensor_parallel_size}")
    if parallel.sequence_parallel:
        args.append("--sequence-parallel")
    if parallel.virtual_pipeline_model_parallel_size and parallel.virtual_pipeline_model_parallel_size > 1:
        layers_per_vstage = a.num_layers // (
            parallel.pipeline_model_parallel_size * parallel.virtual_pipeline_model_parallel_size
        )
        args.append(f"--num-layers-per-virtual-pipeline-stage {layers_per_vstage}")
    if parallel.pipeline_model_parallel_layout:
        layout_str = ",".join(str(n) for n in parallel.pipeline_model_parallel_layout)
        args.append(f"--pipeline-model-parallel-layout '{layout_str}'")

    if parallel.precision is Precision.BF16:
        args.append("--bf16")
    elif parallel.precision is Precision.FP8:
        args.append("--bf16")
        args.append("--fp8-format hybrid")

    if parallel.optimizer_kind is OptimizerKind.DISTRIBUTED_OPTIMIZER:
        args.append("--use-distributed-optimizer")
        args.append("--accumulate-allreduce-grads-in-fp32")
        if parallel.use_precision_aware_optimizer:
            args.append("--use-precision-aware-optimizer")
            args.append(f"--main-grads-dtype {parallel.optimizer_main_grad_dtype}")
            args.append(f"--main-params-dtype {parallel.optimizer_main_param_dtype}")
            args.append(f"--exp-avg-dtype {parallel.optimizer_exp_avg_dtype}")
            args.append(f"--exp-avg-sq-dtype {parallel.optimizer_exp_avg_sq_dtype}")
    elif parallel.optimizer_kind is OptimizerKind.TORCH_FSDP2:
        args.append("--use-torch-fsdp2")
    elif parallel.optimizer_kind is OptimizerKind.MEGATRON_FSDP:
        args.append("--use-megatron-fsdp")

    if workload.recompute_granularity != "none":
        args.append(f"--recompute-granularity {workload.recompute_granularity}")
        if workload.recompute_granularity == "full":
            args.append(f"--recompute-method {workload.recompute_method or 'uniform'}")
            if workload.recompute_num_layers:
                args.append(f"--recompute-num-layers {workload.recompute_num_layers}")

    # Defaults: mock data, no save, no tensorboard, no wandb, log every step.
    args.extend(
        [
            "--mock-data",
            "--tokenizer-type NullTokenizer",
            f"--vocab-size {a.vocab_size}",
            "--log-interval 1",
            "--no-save-optim",
            "--no-save-rng",
            "--use-mcore-models",
        ]
    )
    return args
